if not script.active_mods["Milestones"] then return end

remote.add_interface("per-aspera-ad-astra", {
    milestones_presets = function()
        return {
            ["Per Aspera ad Astra"] = {
                required_mods = {
                    "per-aspera-ad-astra",
                    "lignumis",
                    "bztin",
                    "bzlead",
                    "bztitanium",
                    "scrap-industry",
                    "scrap-chemistry",
                },
                milestones = {
                    {type="group", name="Common Resources"},
                    {type="item",  name="lumber", quantity=1},
                    {type="item",  name="stone-brick", quantity=1},
                    {type="item",  name="iron-plate", quantity=1},
                    {type="item",  name="copper-plate", quantity=1},
                    {type="item",  name="lead-plate", quantity=1},
                    {type="item",  name="tin-plate", quantity=1},
                    {type="item",  name="steel-plate", quantity=1},
                    {type="item",  name="zirconia", quantity=1},
                    {type="item",  name="coke", quantity=1},

                    {type="group", name="Science"},
                    {type="item_consumption",  name="wood-science-pack", quantity=1},
                    {type="item_consumption",  name="steam-science-pack", quantity=1},
                    {type="item_consumption",  name="automation-science-pack", quantity=1},
                    {type="item_consumption",  name="logistic-science-pack", quantity=1},
                    {type="item_consumption",  name="military-science-pack", quantity=1},
                    {type="item_consumption",  name="chemical-science-pack", quantity=1},
                    {type="item_consumption",  name="production-science-pack", quantity=1},
                    {type="item_consumption",  name="utility-science-pack", quantity=1},
                    {type="item_consumption",  name="space-science-pack", quantity=1},
                    {type="item_consumption",  name="metallurgic-science-pack", quantity=1},
                    {type="item_consumption",  name="electromagnetic-science-pack", quantity=1},
                    {type="item_consumption",  name="agricultural-science-pack", quantity=1},
                    {type="item_consumption",  name="cryogenic-science-pack", quantity=1},

                    {type="group", name="Lignumis"},
                    {type="technology",  name="planet-discovery-lignumis", quantity=1},
                    {type="item",  name="peat", quantity=1},
                    {type="item",  name="gold-plate", quantity=1},
                    {type="fluid",  name="wood-pulp", quantity=1},
                    {type="item",  name="cupriavidus-necator", quantity=1},
                    {type="item",  name="gold-quality-catalyst", quantity=1},
                    {type="item",  name="gold-module-3", quantity=1},
                    {type="kill",  name="lignumis-small-wriggler-pentapod", quantity=1},
                    {type="kill",  name="lignumis-medium-wriggler-pentapod", quantity=1},

                    {type="group", name="Nauvis"},
                    {type="technology", name="planet-discovery-nauvis", quantity=1},
                    {type="item", name="uranium-concentrate", quantity=1},
                    {type="item", name="biter-egg", quantity=1},
                    {type="item", name="biolab", quantity=1},
                    {type="kill", name="small-biter", quantity=1},
                    {type="kill", name="medium-biter", quantity=1},
                    {type="kill", name="big-biter", quantity=1},
                    {type="kill", name="behemoth-biter", quantity=1},

                    {type="group", name="Muluna"},
                    {type="technology", name="planet-discovery-muluna", quantity=1},
                    {type="item", name="stone-crushed", quantity=1},
                    {type="item", name="aluminum-plate", quantity=1},
                    {type="fluid",  name="oxygen", quantity=1},
                    {type="item", name="muluna-greenhouse-wood", quantity=1},
                    {type="item", name="cellulose", quantity=1},
                    {type="fluid",  name="tar", quantity=1},
                    {type="item", name="muluna-microcellular-plastic", quantity=1},
                    {type="fluid",  name="muluna-astronomical-data", quantity=1},

                    {type="group", name="Vulcanus"},
                    {type="technology", name="planet-discovery-vulcanus", quantity=1},
                    {type="item", name="calcite", quantity=1},
                    {type="item", name="rough-diamond", quantity=1},
                    {type="item", name="carbonut-seed", quantity=1},
                    {type="item", name="sulfuric-bacteria", quantity=1},
                    {type="item", name="tungsten-carbide", quantity=1},
                    {type="item", name="foundry", quantity=1},
                    {type="item", name="big-mining-drill", quantity=1},
                    {type="item", name="big-crusher", quantity=1},
                    {type="item", name="turbo-transport-belt", quantity=1},
                    {type="kill", name="small-demolisher", quantity=1},
                    {type="kill", name="medium-demolisher", quantity=1},
                    {type="kill", name="big-demolisher", quantity=1},

                    {type="group", name="Fulgora"},
                    {type="technology", name="planet-discovery-fulgora", quantity=1},
                    {type="item", name="recycler", quantity=1},
                    {type="item", name="coralmium", quantity=1},
                    {type="fluid", name="fulgora-oil", quantity=1},
                    {type="fluid", name="holmium-solution", quantity=1},
                    {type="item", name="electromagnetic-plant", quantity=1},
                    {type="item", name="lightning-collector", quantity=1},
                    {type="item", name="charged-iron-matrix", quantity=1},
                    {type="item", name="stone-bacteria", quantity=1},

                    {type="group", name="Gleba"},
                    {type="technology", name="planet-discovery-gleba", quantity=1},
                    {type="item", name="jelly", quantity=1},
                    {type="item", name="yumako-mash", quantity=1},
                    {type="item", name="razorgrass-dried", quantity=1},
                    {type="item", name="biochamber", quantity=1},
                    {type="item", name="slipstack-seed", quantity=1},
                    {type="item", name="fluroflux", quantity=1},
                    {type="item", name="urano-bacteria", quantity=1},
                    {type="item", name="stack-inserter", quantity=1},
                    {type="alias", name="overgrowth-yumako-soil", equals="overgrowth-jellynut-soil", quantity=1},
                    {type="kill", name="small-strafer-pentapod", quantity=1},
                    {type="kill", name="medium-strafer-pentapod", quantity=1},
                    {type="kill", name="big-strafer-pentapod", quantity=1},

                    {type="group", name="Aquilo"},
                    {type="technology", name="planet-discovery-aquilo", quantity=1},
                    {type="fluid", name="ammoniacal-solution", quantity=1},
                    {type="item",  name="lithium-plate", quantity=1},
                    {type="item",  name="algacultural-bay", quantity=1},
                    {type="item", name="cryogenic-plant", quantity=1},
                    {type="item", name="seabloom", quantity=1},
                    {type="item", name="quantum-processor", quantity=1},

                    {type="group", name="By-products and production waste"},                    
                    {type="item",  name="woodchips", quantity=1000, next="x100"},
                    {type="item",  name="sand", quantity=1000, next="x100"},
                    {type="item",  name="iron-scrap", quantity=1000, next="x100"},
                    {type="item",  name="copper-scrap", quantity=1000, next="x100"},
                    {type="item",  name="mech-scrap", quantity=1000, next="x100"},
                    {type="item",  name="circuit-scrap", quantity=1000, next="x100"},                    
                    {type="item",  name="lead-scrap", quantity=1000, next="x100"},
                    {type="item",  name="steel-scrap", quantity=1000, next="x100"},                    
                    {type="item",  name="plastic-bits", quantity=1000, next="x100"},
                    {type="item",  name="titanium-scrap", quantity=1000, next="x100"},
                    {type="item",  name="tungsten-scrap", quantity=1000, next="x100"},
                    {type="item",  name="holmium-scrap", quantity=1000, next="x100"},
                    {type="item",  name="lithium-dust", quantity=1000, next="x100"},
                    {type="item",  name="spoilage", quantity=1000, next="x100"},
                    {type="item",  name="tar", quantity=1000, next="x100"},
                    {type="fluid",  name="butane", quantity=1000, next="x1000"},
                    {type="fluid",  name="sour-gas", quantity=1000, next="x1000"},
                    {type="fluid",  name="naphtha", quantity=1000, next="x1000"},
                    {type="fluid",  name="methane", quantity=1000, next="x1000"},                    
                }
            }
        }
    end
})